create table entity_mapping_table(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
entity_tag varchar2(100) unique,
entity_name varchar2(20),
entity_full_name varchar2(20),
constraint pk_entity_mapping_table primary key(id)
)