create table purity_percentage
(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
date_key date,
entity_tag varchar2(100),
purity_percentage number,
constraints unique_purity_percentage unique(date_key,entity_tag),
constraints pk_purity_percentage primary key(id)
)